require("config.lazy")
require("config.variables")
require("config.env")
require("config.clipboard")
require("config.lsp")
require("config.editorconfig")
require("config.abbrev")
require("config.vscode")
